permissions:
  contents: write
  pull-requests: write

name: AI Correlation PR

on:
  workflow_run:
    workflows: ["Security Scans", "CodeQL Analysis", "Mobile Security Scan", "Compliance Check"]
    types:
      - completed

jobs:
  ai-correlate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir openai pandas sentence-transformers

      - name: Run AI correlate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/ai_correlate.py \
            --checklist requirements/checklist.json \
            --sarif reports/*.sarif \
            --json reports/*.json \
            --out-md reports/audit-summary.md \
            --out-json reports/audit-findings.json

      - name: Create pull request with results
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: ai/bot-correlation
          commit-message: "chore(ai): add correlated security findings"
          title: "AI: Correlated security findings"
          body: |
            Automated correlation of security scans against SEC-CAT* checklist.
            - Generated `reports/audit-summary.md`
            - Produced `reports/audit-findings.json`
          labels: ai, security
          assignees: ${{ github.actor }}
