# AI Correlation workflow: correlates security scan reports with security requirements using AI
# This workflow runs after the security scanning workflows complete successfully.

name: AI Correlation

on:
  workflow_run:
    workflows:
      - "Security Scans"
      - "CodeQL Analysis"
      - "Mobile Security Scan"
      - "Compliance Check"
    types:
      - completed

permissions:
  actions: write        # necesario para download/upload de artifacts
  contents: write
  pull-requests: write

jobs:
  correlate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Download artifacts from triggering run
        uses: actions/download-artifact@v5
        with:
          path: reports
          run-id: ${{ github.event.workflow_run.id }}        # artefactos del run que disparó este workflow
          github-token: ${{ steps.app-token.outputs.token }} # usa tu GitHub App token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (OpenAI SDK nuevo)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip uninstall -y openai || true
          pip install --no-cache-dir --upgrade --force-reinstall "openai>=1.55.0" pandas sentence-transformers

      - name: Run AI correlation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini                 # ✅ reasoning/thinking oficial
          OPENAI_REASONING_EFFORT: medium       # opcional: low|medium|high
          OPENAI_MAX_OUTPUT_TOKENS: "1500"      # opcional
        run: |
          mkdir -p report
          python scripts/ai_correlate.py --checklist requirements/requisitos.json --reports reports --output report/audit-summary.md
          # Duplicado como "json" de compatibilidad (placeholder)
          cp report/audit-summary.md report/audit-findings.json || true

      - name: Upload AI reports
        uses: actions/upload-artifact@v4
        with:
          name: ai-correlation-reports
          path: report/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore(ai): add correlated security findings"
          title: "AI: Correlate security findings"
          body: |
            This pull request contains the correlated security findings generated by the AI assistant.
            The AI mapped the results of security scans against the requirements listed in 'requirements/requisitos.json' and produced an audit summary and findings report.
          branch: ai/correlation-results
