name: Pipeline (orquestador)

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  security-scans:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/security-scans.yml
    secrets: inherit

  mobsf:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/mobsf.yml
    secrets: inherit

  codeql-analysis:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit

  android:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/android.yml
    secrets: inherit

  compliance:
    needs:
      - unit-tests
      - security-scans
      - mobsf
      - codeql-analysis
      - android
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/compliance.yml
    secrets: inherit

  ai-correlation:
    needs:
      - compliance
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/ai-correlation.yml
    secrets: inherit

  # Job "noop" para Dependabot (cumple checks requeridos sin ejecutar la pipeline real)
  noop:
    if: ${{ github.actor == 'dependabot[bot]' || startsWith(github.ref_name, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Dependabot detectado: se omite pipeline (noop).'
