---
name: Pipeline (orquestador)

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

# 👇 Máximo de permisos que heredan los workflows llamados con "uses:"
permissions:
  contents: write          # para checkout/commits (ai-correlation crea rama/commitea)
  pull-requests: write     # para abrir/actualizar PRs (ai-correlation)
  actions: write           # para (descargar/subir) artifacts, etc.
  security-events: write   # para subir SARIF (CodeQL / scanners)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
 
  security_scans:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/security-scans.yml
    secrets: inherit

  codeql_analysis:
    if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit
 
  #mobsf:
   # if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    #uses: ./.github/workflows/mobsf.yml
    #secrets: inherit

  #compliance:
   # needs: [security_scans, mobsf, codeql_analysis]
    #if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    #uses: ./.github/workflows/compliance.yml
    #secrets: inherit

  #ai_correlation:
   # needs: [compliance]
    #if: ${{ github.actor != 'dependabot[bot]' && !startsWith(github.ref_name, 'dependabot/') }}
    #uses: ./.github/workflows/ai-correlation.yml
    #secrets: inherit

  noop:
    if: ${{ github.actor == 'dependabot[bot]' || startsWith(github.ref_name, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - run: "printf '%s\n' 'Dependabot detectado: se omite pipeline (noop).'"
